name: Android CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew :packages:SystemUI:assembleDebug
      
    - name: Run Tests
      run: ./gradlew :packages:SystemUI:test
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: packages/SystemUI/build/outputs/apk/debug/SystemUI-debug.apk
        
    - name: Upload to BrowserStack
      if: github.ref == 'refs/heads/master'
      uses: browserstack/github-actions/upload-app@master
      with:
        app-path: packages/SystemUI/build/outputs/apk/debug/SystemUI-debug.apk
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
